### ISSUE TITLE
Can .json files be checked as well?

### ISSUE THREAD

**Issue by rbaprado** [yitzchak/linter-spell-javascript#4]
I would like to know if .json files can be checked using this package.

**Comment by yitzchak** [comment]
I'll see what I can do.

**Comment by rbaprado** [comment]
Thanks in advance!

Em qua, 24 de ago de 2016 às 18:43, Tarn Burton notifications@github.com
escreveu:

**Comment by yitzchak** [comment]
Fixed in v0.6.0
